### PR TITLE
Update no image available

### PR DESCRIPTION
**Pull request by javiergonzper**

### CODE REVIEW

**Comment by jmaciasportela** [comment]
:+1: 
cc @alfcalmar

**Comment by alfcalmar** [comment]
LGTM

**Comment by jmaciasportela** [comment]
@javiergonzper  add yourself as colaborator https://github.com/solidgear/bulletin/blob/master/colaborators.md

**Comment by javiergonzper** [comment]
I am making the changes from my repo and sending PR

**Pull request merged**
